### ISSUE TITLE
Typo in your Documentation?

### ISSUE THREAD

**Issue by hwater** [mxtommy/SigkSens#25]
Hello From Austria/Danube

is here an typo - "http://A.B.C.D/setSignalKPort?path=/signalk/v1/stream"
should it read - "http://A.B.C.D/setSignalKPath?path=/signalk/v1/stream"

I have Problems to connect the node to my OpenPlotter pi. (v0171)
in nodes serial monitor i get only: 
Starting Delta timer at: 1000ms
Ready!
[WSc] Connected to url: /signalk/v1/stream?subscribe=none

please add some docs about connecting the signal server and client.

--
keep on with this nice little sensor interface.
many greetings
holger

**Comment by mxtommy** [comment]
Good catch! Typo is fixed, thanks! :)

Going by the last line, (WSc) it seems the sensor did in fact connect to the signalk server. I assume your problem is that you don't see any deltas on the server, though that is normal. The sensor will only send deltas for stuff it has a path set for. If you don't have any circuitry connected (see hardware directory for examples) you can test with the "Local" sensor. 

I also just added a bit of expanded documentation in USAGE.md. take a look and let me know! 

Note! With the new digital output "sensor" I just added, I'm running into issues with the size of the config file. Will be fixing it but until it's fixed, please disable unused sensors in config.h (comment out the ENABLE_XYZ lines you don't need)  Will be fixing that later this week! Sorry! Feel free to poke me on the SignalK Dev Slack channel if needed, I'm on there most days 9am-4pm Eastern time.
