### ISSUE TITLE
Output 1-Wire address(es) to Serial Monitor as they're discovered

### ISSUE THREAD

**Issue by ba58smith** [mxtommy/SigkSens#49]
When you scan the 1-wire bus at startup, output the address of any discovered sensors in the Serial Monitor. As it is, you have to run /getSensorInfo to know what the address is, so you can then run /setSensorAttr. Trying to save a step.

**Comment by mxtommy** [comment]
hmmm, not so simple after all :)

On first bootup (before it's ever seen the temp sensor) it will actually print it already. If it's "known" already (already in config) it doesn't print. This is because we scan for new sensors every 30 seconds. (in case of bad connections or so). on subsequent bootups though you should see the address when it prints the config :)

Will leave it as is for now :)

**Comment by ba58smith** [comment]
I hadn't seen it in the config output on each reboot. That's just as good - saves a step. Thanks for pointing it out.
