### ISSUE TITLE
OneWire to Celsius

### ISSUE THREAD

**Issue by hwater** [mxtommy/SigkSens#82]
The "TempK" attribute works well, but setting to "TempC" allways gives an "false" return.
This would be no big Problem, but the "offset" attribute fails also :-(

**Comment by hwater** [comment]
for now i use the "conversion" plugin in SignalK-Server to do the math k to c to solve this.

**Comment by ba58smith** [comment]
TempK is always what SigkSens should output, because that's what Signal K expects - all temps are to be in Kelvin. It's up to the consumer of the data (such as Instrument Panel) to convert to Celsius or Fahrenheit. See the selection in Instrument Panel?
![image](https://user-images.githubusercontent.com/15186790/72261010-62893500-35ea-11ea-8736-fb20817632f9.png)

**Comment by ba58smith** [comment]
Closed.

**Comment by hwater** [comment]
Hello Brian, 
thanks for Answering.

Yes, you are correct, but i found the prepared conversion to TempC in the source of onewire.c...

My Onewire Temperature Sensors from SigkSens in Instruments Panel are not configurable, maybe
there ist an special Flag to set to get them configurable. Some Temperature Sources (aka. Raspi.temp) are
settable as in your Pict. 

For now i use the Calibration plugin in SKServer to do the Maths.

regards
Holger

**Comment by ba58smith** [comment]
The gauges in Instrument Panel are configurable for certain things (like the temperature scale) only if they're recognized as that kind of data (temperature). Look at the Signal K spec (http://signalk.org/specification/1.0.4/doc/vesselsBranch.html) and use a path that's a temperature, then you'll be able to select Celsius in the gauge in Instrument Panel.
